name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t cooltide/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true cooltide/react-test npm test

      - run: docker build -t cooltide/multi-client:v2 ./client
      - run: docker build -t cooltide/multi-nginx ./nginx
      - run: docker build -t cooltide/multi-server ./server
      - run: docker build -t cooltide/multi-worker ./worker

      - run: docker push cooltide/multi-client
      - run: docker push cooltide/multi-nginx
      - run: docker push cooltide/multi-server
      - run: docker push cooltide/multi-worker

      # - name: Generate deployment package
      #   run: zip -r deploy.zip . -x '*.git*'

      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: multi-docker
      #     environment_name: Multi-docker-env
      #     existing_bucket_name: elasticbeanstalk-eu-north-1-054037130643
      #     region: eu-north-1
      #     version_label: ${{ github.sha }}
      #     deployment_package: deploy.zip